from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

from mechcad_harness.artifacts import ArtifactStore, ArtifactType
from mechcad_harness.cad_assembly import (
    CadAssemblyProgram,
    CadComponentInstance,
    CadRigidTransform,
    assembly_hash,
)
from mechcad_harness.cad_program import (
    BasePlateOperation,
    CadPartProgram,
    ThroughHoleOperation,
)
from mechcad_harness.imported_component import (
    ImportedCadComponent,
    resolve_imported_component,
    imported_component_hash,
)
from mechcad_harness.backends.freecad_assembly import FreeCADAssemblyBackend


def _freecad_available() -> bool:
    try:
        from mechcad_harness.backends.freecad import discover_freecad
        return discover_freecad().available
    except Exception:
        return False


FREECAD_CANDIDATE = r"C:\Program Files\FreeCAD 1.1\bin\freecadcmd.exe"


def _make_part(part_id: str) -> CadPartProgram:
    return CadPartProgram(
        part_id=part_id,
        operations=(
            BasePlateOperation(operation_id="base", length_mm=10, width_mm=10, thickness_mm=5),
            ThroughHoleOperation(operation_id="hole1", x_mm=5, y_mm=5, diameter_mm=2),
        ),
    )


def _create_test_step_artifact(store: ArtifactStore, artifact_id: str) -> str:
    step_content = b"""ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('View1 [Generated by MechCAD test]'),'2;1');
FILE_NAME('test_part.step','2026-01-01',(' MechCAD'),(' MechCAD'),'','','');
FILE_SCHEMA(('AUTOMOTIVE_DESIGN'));
ENDSEC;
DATA;
ENDSEC;
END-ISO-10303-21;
"""
    artifact = store.publish(
        artifact_id,
        ArtifactType.STEP,
        f"{artifact_id}.step",
        step_content,
        "test-producer",
        "1.0",
        1,
        "sha256:" + "b" * 64,
    )
    return artifact.sha256


class TestImportedComponentResolution:
    def test_resolve_from_artifact_store(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            store = ArtifactStore(tmpdir, project_id="test-project", run_id="test-run")
            artifact_hash = _create_test_step_artifact(store, "ART-gear-1")
            
            comp = resolve_imported_component(
                artifact_id="ART-gear-1",
                artifact_hash=artifact_hash,
                store=store,
                component_id="gear-1",
            )
            
            assert comp.component_id == "gear-1"
            assert comp.artifact_id == "ART-gear-1"
            assert comp.artifact_hash == artifact_hash
            assert comp.format == "step"
            assert comp.source_revision == 1
            assert comp.source_state_hash == "sha256:" + "b" * 64

    def test_resolve_multiple_imported_components(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            store = ArtifactStore(tmpdir, project_id="test-project", run_id="test-run")
            hash1 = _create_test_step_artifact(store, "ART-gear-1")
            hash2 = _create_test_step_artifact(store, "ART-gear-2")
            
            comp1 = resolve_imported_component(
                artifact_id="ART-gear-1",
                artifact_hash=hash1,
                store=store,
                component_id="gear-1",
            )
            
            comp2 = resolve_imported_component(
                artifact_id="ART-gear-2",
                artifact_hash=hash2,
                store=store,
                component_id="gear-2",
            )
            
            assert comp1.component_id != comp2.component_id
            assert comp1.artifact_id != comp2.artifact_id
            assert comp1.source_revision == comp2.source_revision
            assert comp1.source_state_hash == comp2.source_state_hash


class TestCadAssemblyProgramWithImported:
    def test_assembly_with_imported_components(self):
        part = _make_part("plate")
        imported = ImportedCadComponent(
            component_id="gear-1",
            artifact_id="ART-gear-1",
            artifact_hash="sha256:" + "a" * 64,
            format="step",
            source_revision=1,
            source_state_hash="sha256:" + "b" * 64,
        )
        
        program = CadAssemblyProgram(
            assembly_id="test-assembly",
            parts=(part,),
            imported_components=(imported,),
            instances=(
                CadComponentInstance(instance_id="inst-plate", part_id="plate"),
                CadComponentInstance(instance_id="inst-gear", part_id="gear-1"),
            ),
        )
        
        assert program.assembly_id == "test-assembly"
        assert len(program.parts) == 1
        assert len(program.imported_components) == 1
        assert len(program.instances) == 2
        assert program.has_imported_components
        assert set(program.all_component_ids) == {"plate", "gear-1"}

    def test_assembly_hash_deterministic(self):
        part = _make_part("plate")
        imported = ImportedCadComponent(
            component_id="gear-1",
            artifact_id="ART-gear-1",
            artifact_hash="sha256:" + "a" * 64,
            format="step",
            source_revision=1,
            source_state_hash="sha256:" + "b" * 64,
        )
        
        program1 = CadAssemblyProgram(
            assembly_id="test-assembly",
            parts=(part,),
            imported_components=(imported,),
            instances=(
                CadComponentInstance(instance_id="inst-plate", part_id="plate"),
                CadComponentInstance(instance_id="inst-gear", part_id="gear-1"),
            ),
        )
        
        program2 = CadAssemblyProgram(
            assembly_id="test-assembly",
            parts=(part,),
            imported_components=(imported,),
            instances=(
                CadComponentInstance(instance_id="inst-plate", part_id="plate"),
                CadComponentInstance(instance_id="inst-gear", part_id="gear-1"),
            ),
        )
        
        assert assembly_hash(program1) == assembly_hash(program2)


class TestFreeCADAssemblyBackendImported:
    @pytest.mark.skipif(
        not _freecad_available(),
        reason="FreeCAD not available"
    )
    def test_backend_with_imported_only_components(self, monkeypatch):
        monkeypatch.setenv("MECHCAD_FREECADCMD", FREECAD_CANDIDATE)
        with tempfile.TemporaryDirectory() as tmpdir:
            store = ArtifactStore(tmpdir, project_id="test-project", run_id="test-run")
            from mechcad_harness.backends.freecad import FreeCADBackend

            source = _make_part("imported-source")
            generated = FreeCADBackend().generate_program(
                source,
                tmpdir,
                project_id="test-project",
                run_id="test-run",
                revision=1,
                state_hash="sha256:" + "b" * 64,
            )
            imported = resolve_imported_component(
                artifact_id=generated.step.artifact_id,
                artifact_hash=generated.step.sha256,
                store=store,
                component_id="imported-body",
            )
            program = CadAssemblyProgram(
                assembly_id="imported-only-assembly",
                imported_components=(imported,),
                instances=(
                    CadComponentInstance(instance_id="body-a", part_id="imported-body"),
                    CadComponentInstance(instance_id="body-b", part_id="imported-body", placement=CadRigidTransform(x_mm=20)),
                ),
            )

            result = FreeCADAssemblyBackend().generate_assembly(
                program,
                tmpdir,
                project_id="test-project",
                run_id="test-run",
                revision=1,
                state_hash="sha256:" + "b" * 64,
            )

            assert result.manifest.parts == ()
            assert len(result.manifest.imported_components) == 1
            assert len(result.manifest.instances) == 2
            assert result.fcstd_verification.shape_valid
            assert result.step_verification.shape_valid

    @pytest.mark.skipif(
        not _freecad_available(),
        reason="FreeCAD not available"
    )
    def test_backend_with_imported_components(self, monkeypatch):
        monkeypatch.setenv("MECHCAD_FREECADCMD", FREECAD_CANDIDATE)
        with tempfile.TemporaryDirectory() as tmpdir:
            store = ArtifactStore(tmpdir, project_id="test-project", run_id="test-run")
            # Valid generic STEP produced by the supported generic FreeCAD backend
            # (a plate), not a synthetic header-only fixture. Preserves generic
            # imported-component semantics.
            from mechcad_harness.backends.freecad import FreeCADBackend
            from mechcad_harness.cad_program import BasePlateOperation, CadPartProgram

            imported_program = CadPartProgram(
                part_id="imported-plate",
                operations=(BasePlateOperation(operation_id="base", length_mm=8, width_mm=8, thickness_mm=4),),
            )
            generated = FreeCADBackend().generate_program(
                imported_program,
                tmpdir,
                project_id="test-project",
                run_id="test-run",
                revision=1,
                state_hash="sha256:" + "b" * 64,
            )
            imported = resolve_imported_component(
                artifact_id=generated.step.artifact_id,
                artifact_hash=generated.step.sha256,
                store=store,
                component_id="imported-plate",
            )

            part = _make_part("plate")
            program = CadAssemblyProgram(
                assembly_id="test-assembly",
                parts=(part,),
                imported_components=(imported,),
                instances=(
                    CadComponentInstance(instance_id="inst-plate", part_id="plate"),
                    CadComponentInstance(instance_id="inst-imported", part_id="imported-plate"),
                ),
            )

            backend = FreeCADAssemblyBackend()
            result = backend.generate_assembly(
                program,
                tmpdir,
                project_id="test-project",
                run_id="test-run",
                revision=1,
                state_hash="sha256:" + "b" * 64,
            )

            assert result.fcstd is not None
            assert result.step is not None
            assert result.fcstd_verification.shape_valid
            assert result.step_verification.shape_valid
