from .common import Model, NamedModel, StateBinding
from .issue import Issue, IssueStatus
from .proposal import (
    ChangeProposal,
    ChangeSet,
    ConstraintRequest,
    ProposalStatus,
)
from .run import RunManifest
from .task import AgentResult, AgentTask, TaskStatus
from .validation import ValidationResult, ValidationStatus

_DESIGN_EXPORTS = {
    "Assembly",
    "Component",
    "Constraint",
    "DesignState",
    "Interface",
    "LoadCase",
    "MaterialProfile",
    "Requirement",
}

_STRUCTURAL_EXPORTS = {
    "AcceptanceMaterialAuthorityPolicy",
    "MaximumDisplacementCriterion",
    "StructuralAnalysisDefinition",
    "StructuralAnalysisKind",
    "StructuralBodyAcceleration",
    "StructuralCoordinateFrame",
    "StructuralCriterion",
    "StructuralDof",
    "StructuralFixedSupport",
    "StructuralLoad",
    "StructuralLoadCase",
    "StructuralMaterialAssignment",
    "StructuralMaterialAuthorityDecision",
    "StructuralMaterialAuthorityRejection",
    "StructuralMaterialConversionProvenance",
    "StructuralMaterialPropertyName",
    "StructuralMaterialPropertySnapshot",
    "StructuralPhysicalAssumptions",
    "StructuralPropertyAuthorityRule",
    "StructuralRegionDefinition",
    "StructuralResultField",
    "StructuralResultantForce",
    "StructuralSurfacePressure",
    "YieldSafetyFactorCriterion",
    "evaluate_material_authority_policy",
    "structural_definition_hash",
}

_PHYSICAL_MECHANISM_EXPORTS = {
    "CanonicalAcceptedDesignChoice",
    "CanonicalComponentProperty",
    "CanonicalComponentPropertyAvailability",
    "CanonicalComponentPropertyAuthority",
    "CanonicalComponentSpecification",
    "CanonicalConnectionMeaning",
    "CanonicalDesignChoiceOrigin",
    "CanonicalGeometryFidelity",
    "CanonicalGeometrySourceReference",
    "CanonicalJointPhysicalBinding",
    "CanonicalM10VerificationObligation",
    "CanonicalMechanicalConnection",
    "CanonicalMechanicalConnectionKind",
    "CanonicalPhysicalComponent",
    "CanonicalPhysicalComponentRole",
    "CanonicalPhysicalMechanism",
    "CanonicalPhysicalPairRequirement",
    "CanonicalPlacement",
    "CanonicalPlacementOrigin",
}

_M13_INTERFACE_EXPORTS = {
    "SuppliedInterfaceEvidence",
    "SuppliedInterfaceFact",
    "SuppliedInterfaceTransformRole",
    "SuppliedComponentReferenceFrame",
    "RotationalShaftInterface",
    "MountingFaceInterface",
    "MountingHole",
    "GeometryDerivationAuthorityRole",
    "GeometryDerivationAuthorityFact",
    "GeometryDerivationUnitConversion",
    "GeometryDerivationTransform",
    "InterfaceFactDerivationBinding",
    "InterfaceDerivationProvenance",
    "SuppliedComponentInterfaceDefinition",
    "MaterializedInterfaceResult",
    "MaterializedInterfaceVerifier",
    "MaterializationIntegrityError",
}

_GENERATED_PART_EXPORTS = {
    "AuthorityLocator",
    "ComponentPropertyLocator",
    "CylindricalHubSpecification",
    "DesignSelectionLocator",
    "DirectGeneratedFieldSource",
    "FIELD_SLOTS",
    "GeneratedAttachmentFaceInterface",
    "GeneratedAuthorityError",
    "GeneratedAuthorityInput",
    "GeneratedAuthorityRole",
    "GeneratedAuthoritySourceKind",
    "GeneratedAuthorityView",
    "GeneratedInterfaceDerivation",
    "GeneratedPartFieldBinding",
    "GeneratedPartSpecification",
    "GeneratedReferenceFrame",
    "GeneratedRotationalInterface",
    "GeneratedSelectionNameForm",
    "GENERATED_AUTHORITY_INPUT_ROLES",
    "GENERATED_AUTHORITY_INPUT_SOURCE_KINDS",
    "GENERATED_AUTHORITY_ROLES",
    "GENERATED_AUTHORITY_SOURCE_KINDS",
    "GENERATED_FIELD_BINDING_RULES",
    "GENERATED_FIELD_SLOTS",
    "GENERATED_INTERFACE_DERIVATION_RULES",
    "GENERATED_INTERFACE_RULES",
    "GENERATED_PART_FIELD_SLOTS",
    "GENERATED_PART_RULES",
    "GENERATED_SELECTION_NAME_FORMS",
    "HubBoreSegment",
    "M13_1InterfaceFactLocator",
    "RectangularFrameMemberSpecification",
    "RelationGeneratedFieldSource",
    "SolidCircularShaftSpecification",
    "derive_frame_interfaces",
    "derive_hub_interfaces",
    "derive_shaft_interfaces",
    "evaluate_generated_field_rule",
    "generated_geometry_definition_identities",
    "generated_part_hash",
    "resolve_generated_inputs",
    "selection_hash",
    "validate_generated_interface_registry",
    "value_hash",
    "input_hash",
    "binding_hash",
    "interface_hash",
    "frame_hash",
}

_GENERATED_PLACEMENT_EXPORTS = {
    "PLACEMENT_RULES",
    "CanonicalGeneratedPlacementDerivation",
    "DerivationPlacementRef",
    "DesignVariablePlacementRef",
    "GeneratedFrameAxisRef",
    "GeneratedFrameRef",
    "GeneratedInterfaceRef",
    "GeneratedPlacementDerivation",
    "GeneratedPlacementRotationInput",
    "SourcePlacementRef",
    "compose_poses",
    "invert_pose",
    "place_generated_target",
    "placement_derivations_hash",
    "pose_from_interface",
    "resolve_placement_inputs",
}


def __getattr__(name: str):
    if name == "Evidence":
        from .evidence import Evidence

        value = Evidence
    elif name in _DESIGN_EXPORTS:
        from . import design

        value = getattr(design, name)
    elif name in _STRUCTURAL_EXPORTS:
        from . import structural

        value = getattr(structural, name)
    elif name in _PHYSICAL_MECHANISM_EXPORTS:
        from . import physical_mechanism

        value = getattr(physical_mechanism, name)
    elif name == "GeometryArtifactIdentity":
        from .geometry_identity import GeometryArtifactIdentity

        value = GeometryArtifactIdentity
    elif name in _M13_INTERFACE_EXPORTS:
        from . import supplied_component_interface

        value = getattr(supplied_component_interface, name)
    elif name in _GENERATED_PART_EXPORTS:
        from . import generated_part

        value = getattr(generated_part, name)
    elif name in _GENERATED_PLACEMENT_EXPORTS:
        from . import generated_placement

        value = getattr(generated_placement, name)
    else:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    globals()[name] = value
    return value

__all__ = [
    "AgentResult",
    "AgentTask",
    "AcceptanceMaterialAuthorityPolicy",
    "CanonicalAcceptedDesignChoice",
    "CanonicalComponentProperty",
    "CanonicalComponentPropertyAvailability",
    "CanonicalComponentPropertyAuthority",
    "CanonicalComponentSpecification",
    "CanonicalConnectionMeaning",
    "CanonicalDesignChoiceOrigin",
    "CanonicalGeometryFidelity",
    "CanonicalGeometrySourceReference",
    "CanonicalJointPhysicalBinding",
    "CanonicalM10VerificationObligation",
    "CanonicalMechanicalConnection",
    "CanonicalMechanicalConnectionKind",
    "CanonicalPhysicalComponent",
    "CanonicalPhysicalComponentRole",
    "CanonicalPhysicalMechanism",
    "CanonicalPhysicalPairRequirement",
    "CanonicalPlacement",
    "CanonicalPlacementOrigin",
    "GeometryArtifactIdentity",
    "SuppliedInterfaceEvidence",
    "SuppliedInterfaceFact",
    "SuppliedInterfaceTransformRole",
    "SuppliedComponentReferenceFrame",
    "RotationalShaftInterface",
    "MountingFaceInterface",
    "MountingHole",
    "GeometryDerivationAuthorityRole",
    "GeometryDerivationAuthorityFact",
    "GeometryDerivationUnitConversion",
    "GeometryDerivationTransform",
    "InterfaceFactDerivationBinding",
    "InterfaceDerivationProvenance",
    "SuppliedComponentInterfaceDefinition",
    "MaterializedInterfaceResult",
    "MaterializedInterfaceVerifier",
    "MaterializationIntegrityError",
    "CylindricalHubSpecification",
    "AuthorityLocator",
    "ComponentPropertyLocator",
    "DesignSelectionLocator",
    "DirectGeneratedFieldSource",
    "FIELD_SLOTS",
    "GeneratedAttachmentFaceInterface",
    "GeneratedAuthorityError",
    "GeneratedAuthorityInput",
    "GeneratedAuthorityRole",
    "GeneratedAuthoritySourceKind",
    "GeneratedAuthorityView",
    "GeneratedInterfaceDerivation",
    "GeneratedPartFieldBinding",
    "GeneratedPartSpecification",
    "GeneratedReferenceFrame",
    "GeneratedRotationalInterface",
    "GeneratedSelectionNameForm",
    "GENERATED_AUTHORITY_INPUT_ROLES",
    "GENERATED_AUTHORITY_INPUT_SOURCE_KINDS",
    "GENERATED_AUTHORITY_ROLES",
    "GENERATED_AUTHORITY_SOURCE_KINDS",
    "GENERATED_FIELD_BINDING_RULES",
    "GENERATED_FIELD_SLOTS",
    "GENERATED_INTERFACE_DERIVATION_RULES",
    "GENERATED_INTERFACE_RULES",
    "GENERATED_PART_FIELD_SLOTS",
    "GENERATED_PART_RULES",
    "GENERATED_SELECTION_NAME_FORMS",
    "HubBoreSegment",
    "M13_1InterfaceFactLocator",
    "RectangularFrameMemberSpecification",
    "RelationGeneratedFieldSource",
    "SolidCircularShaftSpecification",
    "derive_frame_interfaces",
    "derive_hub_interfaces",
    "derive_shaft_interfaces",
    "evaluate_generated_field_rule",
    "generated_geometry_definition_identities",
    "generated_part_hash",
    "resolve_generated_inputs",
    "selection_hash",
    "validate_generated_interface_registry",
    "value_hash",
    "input_hash",
    "binding_hash",
    "interface_hash",
    "frame_hash",
    "PLACEMENT_RULES",
    "CanonicalGeneratedPlacementDerivation",
    "DerivationPlacementRef",
    "DesignVariablePlacementRef",
    "GeneratedFrameAxisRef",
    "GeneratedFrameRef",
    "GeneratedInterfaceRef",
    "GeneratedPlacementDerivation",
    "GeneratedPlacementRotationInput",
    "SourcePlacementRef",
    "compose_poses",
    "invert_pose",
    "place_generated_target",
    "placement_derivations_hash",
    "pose_from_interface",
    "resolve_placement_inputs",
    "Assembly",
    "ChangeOperation",
    "ChangeProposal",
    "ChangeSet",
    "Component",
    "Constraint",
    "ConstraintRequest",
    "DesignState",
    "Evidence",
    "Interface",
    "Issue",
    "IssueStatus",
    "LoadCase",
    "MaterialProfile",
    "MaximumDisplacementCriterion",
    "Model",
    "NamedModel",
    "ProposalStatus",
    "Requirement",
    "RunManifest",
    "StateBinding",
    "StructuralAnalysisDefinition",
    "StructuralAnalysisKind",
    "StructuralBodyAcceleration",
    "StructuralCoordinateFrame",
    "StructuralCriterion",
    "StructuralDof",
    "StructuralFixedSupport",
    "StructuralLoad",
    "StructuralLoadCase",
    "StructuralMaterialAssignment",
    "StructuralMaterialAuthorityDecision",
    "StructuralMaterialAuthorityRejection",
    "StructuralMaterialConversionProvenance",
    "StructuralMaterialPropertyName",
    "StructuralMaterialPropertySnapshot",
    "StructuralPhysicalAssumptions",
    "StructuralPropertyAuthorityRule",
    "StructuralRegionDefinition",
    "StructuralResultField",
    "StructuralResultantForce",
    "StructuralSurfacePressure",
    "TaskStatus",
    "ValidationResult",
    "ValidationStatus",
    "YieldSafetyFactorCriterion",
    "evaluate_material_authority_policy",
    "structural_definition_hash",
]
